language: java
jdk: openjdk11

sudo: enabled

before_install:
  - chmod +x mvnw
  - sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';" -uroot
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS wj default charset utf8 COLLATE utf8_general_ci;' -uroot

before_script:
  - sudo mysql -e "use wj;UPDATE user SET password=PASSWORD('Admin123!') WHERE user='root';"  -uroot

sevices:
  - mysql

script:
  - ./mvnw clean install -B