language: java
jdk: openjdk11

sudo: enabled

before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE wj;'
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';";
  # - sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';" -uroot

# before_script:
#   - sudo mysql -e "use mysql;UPDATE user SET authentication_string=PASSWORD('Admin123!') WHERE user='root';"  -uroot

sevices:
  - mysql

script:
  - ./mvnw clean install -B